name: Run tests
on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]
    workflow_dispatch:

permissions:
    contents: read

jobs:
    test:
        runs-on: ubuntu-latest
        environment: testing

        strategy:
            matrix:
                php-version: ["8.2", "8.3"]

        steps:
            - uses: actions/checkout@v4

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php-version }}

            - name: Validate composer.json and composer.lock
              run: composer validate --strict

            - name: Cache Composer packages
              id: composer-cache
              uses: actions/cache@v3
              with:
                  path: vendor
                  key: ${{ runner.os }}-php-${{ matrix.php-version }}-${{ hashFiles('**/composer.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-php-${{ matrix.php-version }}-

            - name: Install dependencies
              run: composer install --prefer-dist --no-progress

            - name: Setup .env file with Zefix credentials
              run: |
                  touch .env
                  echo "ZEFIX_USERNAME=${{ secrets.ZEFIX_USERNAME }}" >> .env
                  echo "ZEFIX_PASSWORD=${{ secrets.ZEFIX_PASSWORD }}" >> .env

            - name: Run test suite
              run: composer run-script test
